# Generated by Django 5.1.4 on 2024-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streamlabs_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
