# Generated by Django 5.1.4 on 2024-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_donation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
