# Generated by Django 5.1.4 on 2024-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_campaign_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
    ]
