# Generated by Django 5.1.4 on 2024-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='tx_hash',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
