# Generated by Django 5.1.4 on 2024-12-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_donation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='streamlabs_token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
