# Generated by Django 5.1.4 on 2024-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_campaign_streamlabs_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='streamlabs_token',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
